# Generated by Django 2.2.1 on 2019-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstLogin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hostelId',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roomNo',
            field=models.IntegerField(blank=True),
        ),
    ]
