# Generated by Django 2.2.1 on 2019-07-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0012_certificaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
