# Generated by Django 2.2.1 on 2019-07-25 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0013_auto_20190725_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='appDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
