# Generated by Django 2.2.1 on 2019-07-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0002_auto_20190720_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hostelId',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roomNo',
            field=models.IntegerField(null=True),
        ),
    ]
