# Generated by Django 2.2.1 on 2019-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0009_auto_20190721_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='raf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='swim',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
