# Generated by Django 2.2.1 on 2019-07-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDash', '0011_auto_20190724_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('certId', models.AutoField(primary_key=True, serialize=False)),
                ('certType', models.CharField(max_length=4)),
                ('isPrepared', models.BooleanField(default=False)),
                ('isDelivered', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDash.UserProfile')),
            ],
        ),
    ]
