# Generated by Django 2.2.1 on 2019-07-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userDash', '0014_auto_20190725_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorId', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userDash.Vendor')),
            ],
        ),
    ]
